=== kiquebarbudo87/kiquebarbudo87.github.io/XML/persona.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,mayor_de_edad?,ciudad,forma_pago+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mayor_de_edad EMPTY>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT forma_pago(#CDATA)>
<!ATTLIST forma_pago tipo (cheque|metálico) "metálico">

=== kiquebarbudo87/kiquebarbudo87.github.io/XML/persona.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "persona.dtd">
<personas>
  <persona>
  <nombre>Enrique</nombre>
  <mayor_de_edad/>
  <ciudad>Córdoba</ciudad>
  <forma_pago tipo = "cheque"></forma_pago>
  </persona>
  <persona>
  <nombre>Quique</nombre>
  <ciudad>Córdoba</ciudad>
  <forma_pago tipo="bizum"></forma_pago>
  </persona>
</personas>
